format:
  html: {toc: true, toc-depth: 3, theme: cosmo, number-sections: false}
  revealjs: {theme: cosmo, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  chapters: [index.qmd, assignments.hw2.utils.qmd, assignments.hw2.q1.qmd, assignments.hw2.q2.qmd, assignments.hw2.q3.qmd, assignments.hw2.q4.qmd, assignments.hw2.q5_6.qmd, assignments.hw2.q7_8.qmd, assignments.hw2.q9_10.qmd, assignments.hw2.cw6_q5.qmd, assignments.hw2.cw6_intuition.qmd]
  title: Homework 2
